backend:
  name: github
  repo: fairglenpto/blognetlify

media_folder: static/assets
public_folder: /assets

collections:
  - name: post
    label: Posts
    folder: src/posts
    create: true
    fields:
      - { name: title, label: Title }
      - { name: date, label: Created, widget: datetime }
      - { name: body, label: Post, widget: markdown, required: false }
      - { name: image, label: Image, widget: image, required: false }